/* Generated by Cython 0.29.6 */

#ifndef __PYX_HAVE__mazelib__generate__TrivialMaze
#define __PYX_HAVE__mazelib__generate__TrivialMaze


#ifndef __PYX_HAVE_API__mazelib__generate__TrivialMaze

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int __pyx_v_7mazelib_8generate_11TrivialMaze_SERPENTINE;
__PYX_EXTERN_C int __pyx_v_7mazelib_8generate_11TrivialMaze_SPIRAL;

#endif /* !__PYX_HAVE_API__mazelib__generate__TrivialMaze */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initTrivialMaze(void);
#else
PyMODINIT_FUNC PyInit_TrivialMaze(void);
#endif

#endif /* !__PYX_HAVE__mazelib__generate__TrivialMaze */
