/* Generated by Cython 0.29.6 */

#ifndef __PYX_HAVE__mazelib__solve__BlindAlley
#define __PYX_HAVE__mazelib__solve__BlindAlley


#ifndef __PYX_HAVE_API__mazelib__solve__BlindAlley

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int __pyx_v_7mazelib_5solve_10BlindAlley_FILLER;
__PYX_EXTERN_C int __pyx_v_7mazelib_5solve_10BlindAlley_SEALER;

#endif /* !__PYX_HAVE_API__mazelib__solve__BlindAlley */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initBlindAlley(void);
#else
PyMODINIT_FUNC PyInit_BlindAlley(void);
#endif

#endif /* !__PYX_HAVE__mazelib__solve__BlindAlley */
